### ISSUE TITLE
Chromedriver somethimes asking where to save file before downloading

### ISSUE THREAD

**Issue by ghost** [justahuman1/blackboard_scraper#1]
Hi Justahuman1,

First of all, I would like to thank you for making this project open-source for anyone to use. I'm in exactly the same situation where I need to download my blackboard courses and this is definitely the solution for me, especially since I have been trying for a while to code my own but could never get it to work with my University's custom blackboard setup.

The only issue I'm currently experiencing is that sometimes when a file is opened in a new tab to begin the download, chrome pops up the dialog box asking for a file location to save in. This kind of breaks the scraper since it just repeats the clicking motion to no avail.

https://sqa.stackexchange.com/questions/2197/how-to-download-a-file-using-seleniums-webdriver 

^ provides some useful info that you may wish to use in the code

If you could fix this issue for me I would be super greatful!

ChemicalNameOfTitin

**Comment by ghost** [comment]
Issue resolved by modifying line 258 :

OLD :         downloads_dir = f'{os.getcwd()}//{new_folder_name}'
NEW :        downloads_dir = f'{os.getcwd()}\\{new_folder_name}'

**Comment by justahuman1** [comment]
I apologize for the late response!

I am glad that you have figured it out. You are correct, I will make that change and add ```os.path.join``` to make it dynamic. Thank you.
